language: python
python:
  - pypy

before_script:
    - sudo chmod a+rwX /etc/passwd /etc/group /etc /usr
    - echo "portage:x:250:250:portage:/var/tmp/portage:/bin/false" >> /etc/passwd
    - echo "portage::250:portage,travis" >> /etc/group
    - mkdir -p travis-overlay /etc/portage/ /usr/portage/distfiles
    - mv !(travis-overlay) travis-overlay/
    - mv .git travis-overlay/
    - wget -O - "https://github.com/gentoo/portage/archive/master.tar.gz" | tar -xz
    - wget -O - "https://github.com/gentoo/gentoo-portage-rsync-mirror/archive/master.tar.gz" | tar xz -C /usr/portage --strip-components=1
    - cp portage-master/cnf/repos.conf /etc/portage/
    - ln -s /usr/portage/profiles/base/ /etc/portage/make.profile
    - wget "http://www.gentoo.org/dtd/metadata.dtd" -O /usr/portage/distfiles/metadata.dtd
    - cd travis-overlay
script:
    - python ../portage-master/bin/repoman full -vdx

notifications:
  irc: "chat.freenode.net#gentoo-science"
