#
# Run repoman via travis
# See https://github.com/mrueg/repoman-travis
#
language: python
cache: pip
python:
    - pypy
env:
    - PORTAGE_VER="2.3.5"
before_install:
    - sudo apt-get -qq update
    - pip install lxml
before_script:
    - sudo chmod a+rwX /etc/passwd /etc/group /etc /usr
    - mkdir -p travis-overlay /etc/portage /usr/portage/distfiles
    - mv !(travis-overlay) travis-overlay/
    - mv .git travis-overlay/
    - wget "https://raw.githubusercontent.com/mrueg/repoman-travis/master/spinner.sh"
    - wget -qO - "https://github.com/gentoo/portage/archive/portage-${PORTAGE_VER}.tar.gz" | tar xz
    - wget -qO - "https://github.com/gentoo-mirror/gentoo/archive/master.tar.gz" | tar xz -C /usr/portage --strip-components=1
    - chmod a+rwx spinner.sh
    - echo "portage:x:250:250:portage:/var/tmp/portage:/bin/false" >> /etc/passwd
    - echo "portage::250:portage,travis" >> /etc/group
    - wget "https://www.gentoo.org/dtd/metadata.dtd" -O /usr/portage/distfiles/metadata.dtd
    - ln -s portage-portage-${PORTAGE_VER}/cnf/repos.conf /etc/portage/repos.conf
    - ln -s /usr/portage/profiles/default/linux/amd64/13.0 /etc/portage/make.profile
    - cd travis-overlay
script:
    - ./../spinner.sh "python ../portage-portage-${PORTAGE_VER}/repoman/bin/repoman full -d"
# You can append own scripts after this line

notifications:
    irc:
        channels: "chat.freenode.net#gentoo-science"
        template:
            - "%{repository} - %{branch} - %{author}: %{commit_subject} - %{message} - Build details : %{build_url}"
        use_notice: true
